### ISSUE TITLE
Immutable.of throw an Exception

### ISSUE THREAD

**Issue by twillouer** [verhas/immutator#1]
Hi,

I discovered your library, and I wondered why `Immutable.of` maintains a signature method that throws an Exception and not a `RuntimeException`.

When the software is running, any access to a setter will anyway throw a `RuntimeException` therefore maintaining the creation of the object with no exception does not seem practical.

Interesting work that said, thank you!

**Comment by verhas** [comment]
The signature of `Immutable.of()` method has no relation to the signature of the method for which it creates a proxy. It may throw a checked exception when the proxy is created. For example it may throw a `FinalCanNotBeExtendedException` when you want to proxy a final class, which is not possible in the actual versions of the Java language and the JVMs. There are other exceptional cases that may be handled by throwing checked exceptions. Since `RuntimeException` is not a checked exception throwing that would not expressively raise the awareness of the programmers using the library and thereof the method `Immutable.of()` that there are exceptional cases that he/she may/need tot handle.

On the other hand, when the proxy is invoked it can not, for technical reasons, throw a checked exception since it must obey the signature of the original method it proxies. The original method may or may not throw a checked exception and therefore the only viable solution to throw an exception in an exceptional case sourcing from the use of the proxy itself is a non-checked, typically `RuntimeException`, which was chosen during the design.

**Comment by twillouer** [comment]
I understand your point of view, but as a user, the "Immutable.of" is well tested with unit test.

So, I need to encapsulate each call to catch Exception, witch is not very attractive.

**Comment by verhas** [comment]
It is wel tested in your case, when you apply the method to objects you can test. However if you develop a library, and the users of the library pass arbitrary objects that are not known by the time you test your code using `Immutable.of()` then you will miss handling the exceptions. In that case you have to catch the exception anyway being it checked or runtime and thus your code will be the same in term of complexity.

On the other hand if the exception is runtime and not checked then you have higher risk forgetting to handle the exception in your library.

If you are sure that you never ever pass any object that may force `Immutable.of()` call to throw exception then create a facade that catches the exception and rethrows it encapsulated in a runtime exception.
