### ISSUE TITLE
How to check, if an object is already an immutable proxy.

### ISSUE THREAD

**Issue by georgy7** [verhas/immutator#6]
To do not make a proxy around another proxy.
To have possibility to do this without any performance decrease:

```
o = makeImmutable(o)
o = makeImmutable(o)
o = makeImmutable(o)
o = makeImmutable(o)
o = makeImmutable(o)
o = makeImmutable(o)
o = makeImmutable(o)
o = makeImmutable(o)
...
```

**Comment by georgy7** [comment]
I thought, I could use `getClass().equals(originalClass)` for the entity objects, that mostly have not any subclasses. But, Hibernate already makes the proxies, so I cannot do that.

**Comment by verhas** [comment]
Although this is not part of the defined functionality as a workaround you can check that the name of the class starts with `PROXY$CLASS$`.

If this functionality is needed you could amend `ProxySourceFactory` to create a Java class that implements a signature interface and then you can check that the object is instance of that interface.

Even in that case being an immutator proxy does not guarantee that you need not create a proxy of it, since immutable proxies may be cascaded: one proxy prohibits access to methods that modify some fields, a next one that forbids access to methods that modify other variables and so on. This, however, is a rare situation, but is in the hands of the caller of Immutable, therefore Immutable itself should not blindly return the passed object in case it is already an immutator proxy.

**Comment by verhas** [comment]
If you are agreeable with that answer I close this ticket.

**Comment by georgy7** [comment]
Ok, thanks for your response.

**Comment by georgy7** [comment]
My solution:

```
public class ReadOnly<T extends DtoOrEntity> {

    private final T value;

    public ReadOnly(T value) {
        try {
            this.value = Immutable.of(value);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    public T getValue() {
        return value;
    }
}
```

I will use the library from this class only and pass ReadOnly as method argument overall. For example:

```
public int someMethod(ReadOnly<Account> account) {
    return account.getValue().getLogin().length();
}

ReadOnly<Account> accountReadOnly = new ReadOnly<>(account);
someMethod(accountReadOnly);
```
